name: Deploy to ECR

on:
 push:
    branches:
     - dev
     - 'feature/**'
     - 'bugfix/**'
     - 'hotfix/**'
jobs:
  build:    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
 
      - name: Create artifact
        id: download-artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: sonarqube/README.md

      - name: Download artifact
        run: |
          cat ${{ steps.download-artifact.outputs.artifact-path }} > my-file-downloaded.txt
          cat my-file-downloaded.txt
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push image to Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: nginx
      #     IMAGE_TAG: dev
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/nginx-fpm/Dockerfile.nginx docker/nginx-fpm/
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
